services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - red_privada

  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: appdb
      DB_USER: app
      DB_PASSWORD: pass
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - red_privada
      - red_publica

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - red_publica

volumes:
  pgdata:

networks:
  red_privada:
  red_publica:

# EJEMPLO CORRECTO

# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: app
#       POSTGRES_PASSWORD: pass
#       POSTGRES_DB: appdb
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - red_privada
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U app -d appdb -h 127.0.0.1"]
#       interval: 5s
#       timeout: 3s
#       retries: 20

#   api:
#     build: ./api
#     environment:
#       DB_HOST: db
#       DB_PORT: "5432"
#       DB_NAME: appdb
#       DB_USER: app
#       DB_PASSWORD: pass
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - "8000:8000"
#     networks:
#       - red_privada
#       - red_publica

#   web:
#     build: ./web
#     depends_on:
#       - api
#     ports:
#       - "8080:80"
#     networks:
#       - red_publica

# volumes:
#   pgdata:

# networks:
#   red_privada:
#   red_publica: